from pydantic import BaseModel, ConfigDict, EmailStr, Field
from typing import Optional, List
from datetime import datetime
from app.models.enums import PaymentStatus, PaymentSource
from app.schemas.course import CourseRead


class PaymentLinkCreateInternal(BaseModel):
    user_name: str = Field(..., min_length=1, max_length=255, description="Full name of student/lead")
    user_email: EmailStr = Field(..., description="Student email address")
    user_phone: Optional[str] = Field(None, max_length=32, description="Phone number with country code")
    course_id: str = Field(..., description="Target course ID")
    due_date: datetime = Field(..., description="Payment due date")
    expires_at: Optional[datetime] = Field(None, description="Payment link expiration timestamp")
    custom_amount_due: Optional[float] = Field(None, description="Override course full price if customized")
    custom_down_payment: Optional[float] = Field(None, description="Override down payment if customized")
    notes: Optional[str] = None


class PaymentLinkRecordExternal(BaseModel):
    user_name: str = Field(..., min_length=1, max_length=255)
    user_email: EmailStr = Field(...)
    user_phone: Optional[str] = None
    course_id: str = Field(...)
    amount_due: float = Field(..., gt=0)
    down_payment_amount: float = Field(default=0.0, ge=0)
    currency: str = "INR"
    payment_link_url: str = Field(..., min_length=5, description="The URL generated by the external portal/gateway")
    external_reference_id: Optional[str] = Field(None, description="Order ID or reference from external portal")
    due_date: datetime = Field(..., description="Due date")
    expires_at: Optional[datetime] = None
    notes: Optional[str] = None


class PaymentLinkFilter(BaseModel):
    status: Optional[PaymentStatus] = None
    course_id: Optional[str] = None
    user_email: Optional[str] = None
    source: Optional[PaymentSource] = None


class PaymentLinkRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: str
    user_name: str
    user_email: str
    user_phone: Optional[str] = None
    course_id: str
    amount_due: float
    down_payment_amount: float
    currency: str
    payment_link_url: str
    source: PaymentSource
    external_reference_id: Optional[str] = None
    status: PaymentStatus
    created_at: datetime
    due_date: datetime
    expires_at: Optional[datetime] = None
    dp_paid_at: Optional[datetime] = None
    converted_at: Optional[datetime] = None
    reminder_count: int
    last_reminder_sent_at: Optional[datetime] = None
    dp_team_alerted: bool
    dp_team_alerted_at: Optional[datetime] = None
    notes: Optional[str] = None
    course: Optional[CourseRead] = None
